language: ruby
rvm:
  - 1.9.3

script:
  - "cd todo/"
  - "rspec"

before_script:
  - "cd todo"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "psql -c 'create database todo_test;' -U postgres"

